export const DIAGNOSTIC_DOMAINS = [
  {
    id: 'business_foundation',
    name: 'Business Foundation',
    description: 'Assess business model, stage, core problem, target customer, revenue model, objectives, and strategic clarity',
    weight: 1.0,
    questions: [
      {
        id: 'bf_1',
        question: 'What is your primary business model?',
        type: 'text' as const,
        required: true,
        evidence_required: false,
        metric: null,
        weight: 1.0,
      },
      {
        id: 'bf_2',
        question: 'What stage is your business currently in?',
        type: 'multiple_choice' as const,
        required: true,
        evidence_required: false,
        metric: null,
        weight: 1.0,
        options: ['Idea', 'Startup', 'Growth', 'Mature', 'Declining'],
      },
      {
        id: 'bf_3',
        question: 'What specific problem does your business solve for customers?',
        type: 'text' as const,
        required: true,
        evidence_required: false,
        metric: null,
        weight: 1.0,
      },
      {
        id: 'bf_4',
        question: 'Who is your target customer? Be as specific as possible.',
        type: 'text' as const,
        required: true,
        evidence_required: false,
        metric: null,
        weight: 1.0,
      },
      {
        id: 'bf_5',
        question: 'What is your primary revenue model?',
        type: 'multiple_choice' as const,
        required: true,
        evidence_required: false,
        metric: null,
        weight: 1.0,
        options: ['One-time sale', 'Subscription', 'Freemium', 'Usage-based', 'Marketplace', 'Advertising', 'Other'],
      },
      {
        id: 'bf_6',
        question: 'What are your top 3 business objectives for the next 12 months?',
        type: 'text' as const,
        required: true,
        evidence_required: false,
        metric: null,
        weight: 1.0,
      },
      {
        id: 'bf_7',
        question: 'On a scale of 1-10, how clear is your strategic direction?',
        type: 'scale' as const,
        required: true,
        evidence_required: false,
        metric: 'strategic_clarity',
        weight: 1.0,
        min: 1,
        max: 10,
      },
    ],
  },
  {
    id: 'market_customer',
    name: 'Market & Customer',
    description: 'Assess customer definition, pain, demand, understanding, market opportunity, competitors, and feedback',
    weight: 1.0,
    questions: [
      {
        id: 'mc_1',
        question: 'How would you describe your ideal customer profile?',
        type: 'text' as const,
        required: true,
        evidence_required: false,
        metric: null,
        weight: 1.0,
      },
      {
        id: 'mc_2',
        question: 'What is the primary pain point your customers experience?',
        type: 'text' as const,
        required: true,
        evidence_required: false,
        metric: null,
        weight: 1.0,
      },
      {
        id: 'mc_3',
        question: 'How do you currently validate customer demand?',
        type: 'text' as const,
        required: true,
        evidence_required: false,
        metric: null,
        weight: 1.0,
      },
      {
        id: 'mc_4',
        question: 'How well do you understand your customers\' needs? (1-10)',
        type: 'scale' as const,
        required: true,
        evidence_required: false,
        metric: 'customer_understanding',
        weight: 1.0,
        min: 1,
        max: 10,
      },
      {
        id: 'mc_5',
        question: 'What is the estimated market size for your solution?',
        type: 'text' as const,
        required: false,
        evidence_required: false,
        metric: null,
        weight: 1.0,
      },
      {
        id: 'mc_6',
        question: 'Who are your top 3 competitors?',
        type: 'text' as const,
        required: true,
        evidence_required: false,
        metric: null,
        weight: 1.0,
      },
      {
        id: 'mc_7',
        question: 'How do you collect customer feedback?',
        type: 'multiple_choice' as const,
        required: true,
        evidence_required: false,
        metric: null,
        weight: 1.0,
        options: ['Surveys', 'Interviews', 'Reviews', 'Support tickets', 'No formal process', 'Other'],
      },
    ],
  },
  {
    id: 'offer_value',
    name: 'Offer & Value',
    description: 'Assess offer clarity, customer outcome, pricing, packaging, differentiation, perceived value, and revenue opportunities',
    weight: 1.0,
    questions: [
      {
        id: 'ov_1',
        question: 'What is your core product or service offering?',
        type: 'text' as const,
        required: true,
        evidence_required: false,
        metric: null,
        weight: 1.0,
      },
      {
        id: 'ov_2',
        question: 'What specific outcome does your customer achieve?',
        type: 'text' as const,
        required: true,
        evidence_required: false,
        metric: null,
        weight: 1.0,
      },
      {
        id: 'ov_3',
        question: 'What is your pricing model?',
        type: 'text' as const,
        required: true,
        evidence_required: false,
        metric: null,
        weight: 1.0,
      },
      {
        id: 'ov_4',
        question: 'How do you package your offerings?',
        type: 'text' as const,
        required: false,
        evidence_required: false,
        metric: null,
        weight: 1.0,
      },
      {
        id: 'ov_5',
        question: 'What makes your offer different from competitors?',
        type: 'text' as const,
        required: true,
        evidence_required: false,
        metric: null,
        weight: 1.0,
      },
      {
        id: 'ov_6',
        question: 'How do customers perceive the value of your offering? (1-10)',
        type: 'scale' as const,
        required: true,
        evidence_required: false,
        metric: 'perceived_value',
        weight: 1.0,
        min: 1,
        max: 10,
      },
      {
        id: 'ov_7',
        question: 'Do you have upsell or cross-sell opportunities?',
        type: 'yes_no' as const,
        required: false,
        evidence_required: false,
        metric: null,
        weight: 1.0,
      },
    ],
  },
  {
    id: 'positioning_brand',
    name: 'Positioning & Brand',
    description: 'Assess positioning, differentiation, messaging, credibility, perceived value, brand consistency, and market recognition',
    weight: 1.0,
    questions: [
      {
        id: 'pb_1',
        question: 'How would you describe your market positioning?',
        type: 'text' as const,
        required: true,
        evidence_required: false,
        metric: null,
        weight: 1.0,
      },
      {
        id: 'pb_2',
        question: 'What is your unique value proposition?',
        type: 'text' as const,
        required: true,
        evidence_required: false,
        metric: null,
        weight: 1.0,
      },
      {
        id: 'pb_3',
        question: 'How consistent is your messaging across channels? (1-10)',
        type: 'scale' as const,
        required: true,
        evidence_required: false,
        metric: 'messaging_consistency',
        weight: 1.0,
        min: 1,
        max: 10,
      },
      {
        id: 'pb_4',
        question: 'What establishes your credibility in the market?',
        type: 'text' as const,
        required: true,
        evidence_required: false,
        metric: null,
        weight: 1.0,
      },
      {
        id: 'pb_5',
        question: 'How would you rate your brand recognition? (1-10)',
        type: 'scale' as const,
        required: true,
        evidence_required: false,
        metric: 'brand_recognition',
        weight: 1.0,
        min: 1,
        max: 10,
      },
    ],
  },
  {
    id: 'marketing_demand',
    name: 'Marketing & Demand',
    description: 'Measure reach, leads, qualified leads, acquisition channels, lead quality, consistency, cost, and ROI',
    weight: 1.0,
    questions: [
      {
        id: 'md_1',
        question: 'How many leads did you generate last month?',
        type: 'number' as const,
        required: true,
        evidence_required: true,
        metric: 'monthly_leads',
        weight: 1.0,
      },
      {
        id: 'md_2',
        question: 'How many of those leads were qualified?',
        type: 'number' as const,
        required: true,
        evidence_required: true,
        metric: 'qualified_leads',
        weight: 1.0,
      },
      {
        id: 'md_3',
        question: 'What are your primary acquisition channels?',
        type: 'text' as const,
        required: true,
        evidence_required: false,
        metric: null,
        weight: 1.0,
      },
      {
        id: 'md_4',
        question: 'How consistent is your marketing activity? (1-10)',
        type: 'scale' as const,
        required: true,
        evidence_required: false,
        metric: 'marketing_consistency',
        weight: 1.0,
        min: 1,
        max: 10,
      },
      {
        id: 'md_5',
        question: 'What is your average customer acquisition cost?',
        type: 'currency' as const,
        required: false,
        evidence_required: true,
        metric: 'customer_acquisition_cost',
        weight: 1.0,
      },
      {
        id: 'md_6',
        question: 'Do you track marketing ROI?',
        type: 'yes_no' as const,
        required: true,
        evidence_required: false,
        metric: null,
        weight: 1.0,
      },
    ],
  },
  {
    id: 'sales_conversion',
    name: 'Sales & Conversion',
    description: 'Measure lead to conversation to proposal to sale, including response time, qualification, process, follow-up, closing, and conversion',
    weight: 1.0,
    questions: [
      {
        id: 'sc_1',
        question: 'How many sales did you close last month?',
        type: 'number' as const,
        required: true,
        evidence_required: true,
        metric: 'monthly_sales',
        weight: 1.0,
      },
      {
        id: 'sc_2',
        question: 'What is your average response time to leads?',
        type: 'text' as const,
        required: true,
        evidence_required: false,
        metric: null,
        weight: 1.0,
      },
      {
        id: 'sc_3',
        question: 'Do you have a documented sales process?',
        type: 'yes_no' as const,
        required: true,
        evidence_required: false,
        metric: null,
        weight: 1.0,
      },
      {
        id: 'sc_4',
        question: 'What is your lead-to-proposal conversion rate?',
        type: 'percentage' as const,
        required: false,
        evidence_required: true,
        metric: 'lead_to_proposal_rate',
        weight: 1.0,
      },
      {
        id: 'sc_5',
        question: 'What is your proposal-to-sale conversion rate?',
        type: 'percentage' as const,
        required: false,
        evidence_required: true,
        metric: 'proposal_to_sale_rate',
        weight: 1.0,
      },
      {
        id: 'sc_6',
        question: 'How do you handle follow-ups?',
        type: 'text' as const,
        required: true,
        evidence_required: false,
        metric: null,
        weight: 1.0,
      },
      {
        id: 'sc_7',
        question: 'What is your average transaction value?',
        type: 'currency' as const,
        required: true,
        evidence_required: true,
        metric: 'average_transaction_value',
        weight: 1.0,
      },
    ],
  },
  {
    id: 'operations_delivery',
    name: 'Operations & Delivery',
    description: 'Assess processes, systems, capacity, quality control, delivery time, technology, customer experience, and operational waste',
    weight: 1.0,
    questions: [
      {
        id: 'od_1',
      question: 'How would you describe your operational processes?',
        type: 'text' as const,
        required: true,
        evidence_required: false,
        metric: null,
        weight: 1.0,
      },
      {
        id: 'od_2',
        question: 'What systems do you use to manage operations?',
        type: 'text' as const,
        required: true,
        evidence_required: false,
        metric: null,
        weight: 1.0,
      },
      {
        id: 'od_3',
        question: 'What is your current operational capacity?',
        type: 'text' as const,
        required: true,
        evidence_required: false,
        metric: null,
        weight: 1.0,
      },
      {
        id: 'od_4',
        question: 'How do you ensure quality control?',
        type: 'text' as const,
        required: true,
        evidence_required: false,
        metric: null,
        weight: 1.0,
      },
      {
        id: 'od_5',
        question: 'What is your average delivery time?',
        type: 'text' as const,
        required: true,
        evidence_required: false,
        metric: null,
        weight: 1.0,
      },
      {
        id: 'od_6',
        question: 'How would you rate your customer experience? (1-10)',
        type: 'scale' as const,
        required: true,
        evidence_required: false,
        metric: 'customer_experience',
        weight: 1.0,
        min: 1,
        max: 10,
      },
      {
        id: 'od_7',
        question: 'Where do you see operational waste?',
        type: 'text' as const,
        required: false,
        evidence_required: false,
        metric: null,
        weight: 1.0,
      },
    ],
  },
  {
    id: 'financial_engine',
    name: 'Financial Engine',
    description: 'Capture and calculate financial metrics including revenue, profit, margins, cash flow, and customer metrics',
    weight: 1.0,
    questions: [
      {
        id: 'fe_1',
        question: 'What is your monthly revenue?',
        type: 'currency' as const,
        required: true,
        evidence_required: true,
        metric: 'monthly_revenue',
        weight: 1.0,
      },
      {
        id: 'fe_2',
        question: 'What is your monthly gross profit?',
        type: 'currency' as const,
        required: true,
        evidence_required: true,
        metric: 'monthly_gross_profit',
        weight: 1.0,
      },
      {
        id: 'fe_3',
        question: 'What are your monthly operating costs?',
        type: 'currency' as const,
        required: true,
        evidence_required: true,
        metric: 'monthly_operating_costs',
        weight: 1.0,
      },
      {
        id: 'fe_4',
        question: 'What is your current cash balance?',
        type: 'currency' as const,
        required: true,
        evidence_required: true,
        metric: 'cash_balance',
        weight: 1.0,
      },
      {
        id: 'fe_5',
        question: 'What are your total receivables?',
        type: 'currency' as const,
        required: false,
        evidence_required: true,
        metric: 'receivables',
        weight: 1.0,
      },
      {
        id: 'fe_6',
        question: 'What are your total payables?',
        type: 'currency' as const,
        required: false,
        evidence_required: true,
        metric: 'payables',
        weight: 1.0,
      },
      {
        id: 'fe_7',
        question: 'Do you have any outstanding debt?',
        type: 'yes_no' as const,
        required: true,
        evidence_required: false,
        metric: null,
        weight: 1.0,
      },
    ],
  },
  {
    id: 'people_leadership',
    name: 'People & Leadership',
    description: 'Assess founder dependency, team capacity, skills, delegation, accountability, decision making, leadership, and culture',
    weight: 1.0,
    questions: [
      {
        id: 'pl_1',
        question: 'How dependent is the business on the founder? (1-10)',
        type: 'scale' as const,
        required: true,
        evidence_required: false,
        metric: 'founder_dependency',
        weight: 1.0,
        min: 1,
        max: 10,
      },
      {
        id: 'pl_2',
        question: 'How would you describe your team capacity?',
        type: 'text' as const,
        required: true,
        evidence_required: false,
        metric: null,
        weight: 1.0,
      },
      {
        id: 'pl_3',
        question: 'What skills gaps exist in your team?',
        type: 'text' as const,
        required: true,
        evidence_required: false,
        metric: null,
        weight: 1.0,
      },
      {
        id: 'pl_4',
        question: 'How effectively do you delegate? (1-10)',
        type: 'scale' as const,
        required: true,
        evidence_required: false,
        metric: 'delegation_effectiveness',
        weight: 1.0,
        min: 1,
        max: 10,
      },
      {
        id: 'pl_5',
        question: 'How is accountability structured in the organization?',
        type: 'text' as const,
        required: true,
        evidence_required: false,
        metric: null,
        weight: 1.0,
      },
      {
        id: 'pl_6',
        question: 'How would you describe your decision-making process?',
        type: 'text' as const,
        required: true,
        evidence_required: false,
        metric: null,
        weight: 1.0,
      },
      {
        id: 'pl_7',
        question: 'How would you describe your company culture?',
        type: 'text' as const,
        required: true,
        evidence_required: false,
        metric: null,
        weight: 1.0,
      },
    ],
  },
  {
    id: 'strategy_execution',
    name: 'Strategy & Execution',
    description: 'Assess goals, priorities, strategic clarity, resource allocation, competitive advantage, execution discipline, measurement, and adaptability',
    weight: 1.0,
    questions: [
      {
        id: 'se_1',
        question: 'What are your top 3 strategic goals?',
        type: 'text' as const,
        required: true,
        evidence_required: false,
        metric: null,
        weight: 1.0,
      },
      {
        id: 'se_2',
        question: 'How do you prioritize initiatives?',
        type: 'text' as const,
        required: true,
        evidence_required: false,
        metric: null,
        weight: 1.0,
      },
      {
        id: 'se_3',
        question: 'How clear is your strategic direction? (1-10)',
        type: 'scale' as const,
        required: true,
        evidence_required: false,
        metric: 'strategic_clarity',
        weight: 1.0,
        min: 1,
        max: 10,
      },
      {
        id: 'se_4',
        question: 'How do you allocate resources?',
        type: 'text' as const,
        required: true,
        evidence_required: false,
        metric: null,
        weight: 1.0,
      },
      {
        id: 'se_5',
        question: 'What is your competitive advantage?',
        type: 'text' as const,
        required: true,
        evidence_required: false,
        metric: null,
        weight: 1.0,
      },
      {
        id: 'se_6',
        question: 'How would you rate your execution discipline? (1-10)',
        type: 'scale' as const,
        required: true,
        evidence_required: false,
        metric: 'execution_discipline',
        weight: 1.0,
        min: 1,
        max: 10,
      },
      {
        id: 'se_7',
        question: 'How do you measure progress?',
        type: 'text' as const,
        required: true,
        evidence_required: false,
        metric: null,
        weight: 1.0,
      },
      {
        id: 'se_8',
        question: 'How adaptable is your strategy to market changes? (1-10)',
        type: 'scale' as const,
        required: true,
        evidence_required: false,
        metric: 'adaptability',
        weight: 1.0,
        min: 1,
        max: 10,
      },
    ],
  },
]

export type QuestionType = 'text' | 'number' | 'currency' | 'percentage' | 'yes_no' | 'multiple_choice' | 'scale' | 'date'

export interface DiagnosticQuestion {
  id: string
  question: string
  type: QuestionType
  required: boolean
  evidence_required: boolean
  metric: string | null
  weight: number
  options?: string[]
  min?: number
  max?: number
}

export interface DiagnosticDomain {
  id: string
  name: string
  description: string
  weight: number
  questions: DiagnosticQuestion[]
}
